version: '2'

services:

  wordpress:
    build:
      context: ./
    ports:
      - 8080:80
    volumes:
      - ./data:/var/www/html
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mariadb
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    ports:
      - 33067:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
